config/routes.rb
Rails.application.routes.draw do
  get 'index/input'
  get 'index/output'
  root 'index#input'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def input
  end

  def output
    @a = params[:num].to_f
    if @a <= 0
      @error = 'Ошибка!'
    else
      @x = []
      @x[0] = @a
      i = 1
      while (@x[i-1]**2-@a)/@a > 0.001
        @x[i] = 0.5*(@x[i-1]+@a/@x[i-1])
        i += 1
      end
      @x
    end
    respond_to do |format|
      format.html
      format.json do
        render json:
          {num: @x, error: @error, }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/index/input.html.erb
<h1>Ввод значений</h1>
<p>Пожалуйста, введите в форму ниже, квадратный корень какого положительного числa вы хотели бы вычислить:</p>
<form action = "<%= index_output_url %>" method = "get" id = "first">
    <input name ="num" type="text" min ="1">
    <input type="submit" value="Вычислить">
</form>
<br>
<%= form_with url: index_output_url+".json", method: :get, id: "second" do |form| %>
    <%= form.number_field :num, min: 1%>
    <input type = "button" value = "Вычислить на этой странице" id = "ajaxsend">
<% end %>
<div id="result"></div> 

<script>
    let out_url = "<%= index_output_url %>" + ".json"
    const element = document.querySelector("#second #ajaxsend")
    element.onclick = function(){
        const param_str = "num=" + document.querySelector("#second #num").value
        let my_JSON_object = {}
        let http_request = new XMLHttpRequest()
        http_request.open("GET",out_url + "?" + param_str)
        http_request.onreadystatechange = function () {
            var done = 4, ok = 200;
            if (http_request.readyState == done && http_request.status == ok) {
                my_JSON_object = JSON.parse(http_request.responseText);
                show_result(my_JSON_object);
            }
        };
        http_request.send();
    }
    function show_result(data){
        const err = data.error
        const value = data.num
        let result = document.querySelector("#result")
        result.innerHTML = ""
        result.insertAdjacentHTML('afterbegin', '<h1>Вывод результатов</h1>')
        if (err != null){
            result.insertAdjacentHTML('beforeend', '<p>Ошибка!</p>')
        }
        else {
            create_table(value, result)
        }
    }
    function create_table(data, place){
        row_amount = data.length
        place.insertAdjacentHTML('beforeend','<table id = "restable">')
        table_place = document.querySelector('#restable')
        for (let i = 0; i < row_amount; ++i){
            table_place.insertAdjacentHTML('beforeend',`<tr> <td>${i+1}</td> <td>${data[i].toFixed(5)}</td> </tr>`)
        }
        place.insertAdjacentHTML('beforeend',`<p>Конечный результат: ${data[row_amount-1].toFixed(5)}</p>`)
    }
</script>

app/views/index/output.html.erb
<h1>Вывод значений</h1>

<% if @error then%>
    <p><%=@error%></p>
<% else %>
    <p style="font-weigth:bold"> Вычисление квадратного корня <%=@a%> </p>
    <p> Промежуточные результаты: </p>
    <table>
    <%i = 1%>
        <% @x.each do |el| %>
            <tr>
            <td><%=i%></td>
            <td><%=el.round(5)%></td>
            <%i += 1%>
            </tr>
        <%end%>
    </table>
    <p>Конечный результат: <%=@x.last.round(5)%><p>
<%end%>
<a href="/index/input"> Вернуться назад к вводу </a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laba9</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1> ЛР 9. AJAX</h1>
    <div style="max-width:800px">
    <p style="text-align: justify">
    <ul>
    <li>При помощи Javascript модифицировать код ЛР 8 таким образом, чтобы для отображения результатов вычисления браузер не выполнял полную перезагрузку страницы.</li>
    <li>Сформировать тесты для проверки работы программы при помощи Katalon Recorder / Selenium Webdriver.</li>
    </ul>
    <br><br>
    <span style="font-weight:bold">Tекст задания: </span><br><br>
    Метод Ньютона – Рафсона основывается на утверждении, что квадратный корень числа А можно найти с помощью рекурентной формулы:<br>
    <code style="font-weight:bold">x(i+1) = 1/2*(x(i)+A/x(i))</code>,где A — положительное число, x(i) — текущее приближение квадратного корня, x(i+1) — очередное приближенное значение
    квадратного корня из числа A. Написать программу, определяющую квадратный корень заданных чисел, используя приведенную формулу. 
    Прекращение процесса вычисления предусмотреть при выполнении условия
    <code style="font-weight:bold">(x(i+1)^2-A)/A < 0.001</code>.<br>
    Вывести промежуточные итерации и полученный результат.
    </p>
    </div>
    <div style = "border: 1px solid black; max-width:750px; padding: 0px 25px 25px">
      <%= yield %>
    </div>
  </body>
</html>